name: Lint

on:
  push:
    branches: [master]
    paths: ["**.js", "**.ts", "**.md", ".json", ".yml"]
  pull_request:
    branches: [master]
    paths: ["**.js", "**.ts", "**.md", ".json", ".yml"]

jobs:
  Lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Yarn
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Linter
        run: yarn lint:check
        env:
          CI: true
