name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not been commented on for 1 month.

            The resources of the Joodle team are limited, and so we are asking for your help.

            If you can still reproduce this error on the `develop` or `master` branches,
            please reply with all of the information you have about it in order to keep the issue open.

            Thank you for all your contributions.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs.

            Thank you for your contributions.
          stale-issue-label: stale
          stale-pr-label: stale
          days-before-stale: 30
          days-before-close: 5
          exempt-issue-labels: "exploit"
          exempt-pr-labels: "exploit"
