name: Test

on:
  push:
    branches: [master]
    paths: ["**.js", "**.ts"]
  pull_request:
    branches: [master]
    paths: ["**.js", "**.ts"]

jobs:
  Test:
    runs-on: ubuntu-latest

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Yarn
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: yarn test
        env:
          CI: true
